openapi: "3.0.0"
info:
  title: "[3팀 version3.0] chorok"
  version: "1.0.0"
  description: "3팀 version 3.0의 API 문서입니다. "
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []    
host: http://localhost:3000
servers:
  - url: http://localhost:5001
paths:
  /posts:
    $ref: "./post/posts.yaml"
  /posts/{id}:
    $ref: "./post/posts-id.yaml"
  /comments:
    $ref: "./comment/comments.yaml"
  /comments/{id}:
    $ref: "./comment/comments-id.yaml"